config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root "users#show"
  root "homes#index"
resources :books
resources :users 
resources :post_images

get "home/about" => "homes#about",as: "about_home"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true
	validates :body, length: {maximum: 200}
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :user
	attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  has_one :post_image

  attachment :profile_image

  #以下を追加
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

# 登録時にメールアドレスを不要とする
  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	

	before_action :configure_permitted_parameters, if: :devise_controller?

	def configure_permitted_parameters
    	devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name,:email, :password, :password_confirmation) }
    	devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :password, :password_confirmation) }
    end

    def after_sign_in_path_for(resource) 
    user_path(current_user.id)
  	end
  

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	
before_action :authenticate_user!

def create
	@book = Book.new(book_params)
	@book.user_id = current_user.id
	if @book.save
	redirect_to book_path(@book.id),notice: "You have creatad book successfully."
    else
    @user = current_user
    @books = Book.all
    render :index
    end
end

def index
	@book = Book.new
	@books = Book.all
	@user = current_user
end

def show
	@book = Book.find(params[:id])
	@user = @book.user
end

def edit
	@book = Book.find(params[:id])
	if @book.user != current_user
		redirect_to books_path
	end

end

def update
	@book = Book.find(params[:id])
	if @book.update(book_params)
	redirect_to book_path(@book.id),notice: "You have updated book successfully."
    else
    render :edit
 	end

end 

def destroy
	@book = Book.find(params[:id])
	@book.destroy
	redirect_to books_path
end 

private
def book_params
	params.require(:book).permit(:title,:body)
end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index

	end

	def about

	end
end

app/controllers/post_image_controller.rb
class PostImageController < ApplicationController

def new 
	@post_iamge = PostImage.new
end 

def create
	@post_iamge = PostImage.new(params[:id])
	@post_image.save
end

private
def post_image_params
params.require(:post_iamge).permit(:image)
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
  	@users = User.all
  	@user = current_user
  	@book = Book.new
  end

  def show
  	@user = User.find(params[:id])
  	@books = Book.where(user_id:@user)
  	@book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  	redirect_to user_path(@user.id),notice:"You have updated user successfully"
    else
    render :edit
    end
  end


private
def user_params
	params.require(:user).permit(:name,:introduction,:profile_image)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_image_helper.rb
module PostImageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb

<h2>Editing Book</h2>
<% if @book.errors.any? %>
	<h1><%= pluralize(@book.errors.count, "error") %>prohibited this obj from being saved:</h1>
	<%= @book.errors.full_messages.each do |message| %>
	<li><%= message %></li>
	<% end %>
<% end %>

<%= form_for(@book) do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_area :body %>

<%= f.submit "Update Book" %>
<br>	
<%= link_to "Show",book_path(@book.id) %>
<%= link_to "Back",books_path%>
<% end %>

app/views/books/index.html.erb
<div class="container">
	<div class="row">	
		<div class="col-xs-3">
<% if @book.errors.any? %>
	<h1><%= pluralize(@book.errors.count, "error") %><br>prohibited this obj from being saved:</h1>
	<% @book.errors.full_messages.each do |message| %>
	<li><%= message %></li>
	<% end %>
<% end %>

<h1>User info</h1>
<%= attachment_image_tag @user,:profile_image,:fill,60,60,format:"jpg", fallback: "no_image.jpg", size:'60x60' %>
<table class = "table">
	<tbody>	
		<tr>		
				<td>name</td>
				<td><%= @user.name %></td>
		</tr>
		<tr>
				<td>introduction</td>
				<td><%= @user.introduction %></td>
		</tr>
	</tbody>
</table>
<% if @user.id == current_user.id %>
<%= link_to edit_user_path(@user.id) do %>
<div class="btn-group" role="group">
	<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
</div>
<% end %>
<% end %>

<h1>New book</h1>
<%= form_for(@book) do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opininion</h4>
<%= f.text_area :body %>
<%= f.submit "Create Book" %>
<% end %>
</div>
<div class="col-xs-9">	

<h1>Books</h1>

<table class="table">
<tr>
	<th></th>
	<th>Title</th>
	<th>Opinion</th>
</tr>	
<% @books.each do |book| %>
<tr>
	<%= link_to user_path(book.user.id) do %>
	<td><%= attachment_image_tag book.user,:profile_image,:fill,60,60,format:"jpg", fallback: "no_image.jpg", size:'60x60' %></td>
	<% end %>
	<td><%= link_to book.title,book_path(book.id) %></td>
	<td><%= book.body %></td>
</tr>
<% end %>
</table>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">	
		<div class="col-xs-3">	
<%# if flash[:notice] %>
	<p><%# flash[:notice] %></p>
<%# end %>

<!-- ユーザ情報 -->
<h2>User info</h2>
<%= attachment_image_tag @user,:profile_image,:fill,60,60,format:"jpg", fallback: "no_image.jpg", size:'60x60' %>
<table class="table">
	<tbody>
		<tr>	
		<td><h4>name</h4></td>
		<td><%= @user.name %></td>
		</tr>
		<tr>	
		<td>introduction</td>
		<td><%= @user.introduction%></td>
		</tr>
	</tbody>	
</table>
<% if @user.id == current_user.id %>
<%= link_to edit_user_path(@user.id) do %>
<div class="btn-group" role="group">
	<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
</div>
<% end %>
<% end %>

<!-- 新規投稿 -->
<h2>New book</h2>
<%= form_for(@book) do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_area :body %>

<%= f.submit "Create Book" %>
<% end %>
</div>
<div class="col-xs-9">

<h2>Book detail</h2>
<table class="table">
	<tbody>	
	<tr>
		<td><%= attachment_image_tag @user,:profile_image,:fill,60,60,format:"jpg", fallback: "no_image.jpg", size:'60x60' %><br><%= link_to @user.name,user_path(@user.id)%></td>
		<td><%= link_to @book.title,book_path(@book.id) %></td>
		<td><%= @book.body %></td>
		<% if @user.id == current_user.id %>
		<td >
			<%= link_to  edit_book_path(@book.id) do %>
					<button type="button" class="btn btn-default btn-block" style="background-color:#33CC00;">Edit</button>
			<% end %>
		</td>
		<td >
			<%= link_to book_path(@book.id),method: :delete,data:{confirm: "削除しますか？"} do %>
			<button type="button" class="btn btn-default btn-block" style="background-color:#FF3300">Destroy</button>
			<% end %>
		</td>
		<% end %>
	</tr>
	</tbody>
</table>
</div>
</div>





app/views/homes/about.html.erb
<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>	Bookers! </strong></h1>
<p>CopyRight Infratop.inc</p>

app/views/homes/index.html.erb

<div class="container">	
			<div class="mx-auto" >	
				<h1>Welcome to "Log in"<span class="glyphicon glyphicon-book" aria-hidden="true"></span> <strong>Bookers  !!	</strong></h1>
				<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span> <strong>	Bookers,</strong></p>
				<p>you can share and exchange your opinions,inpressions,and emotions</p>
				<p>about various books!</p>
				<div>
						
				
						<%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-block' %>
						<%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary btn-block' %>
				</div>
			</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header style="background-color:black;">
      <div class = "container">
        <div class = "row">
          <div class = "col-xs-4">
            <span style="color:white;">Bookers</span>
          </div>
          <div class = "col-xs-8">
            <% if user_signed_in? %>
            
            <ul class = "nav navbar-nav navbar-right">
              <li>
              <%= link_to user_path(current_user.id) do %>
              <span class="glyphicon glyphicon-home" aria-hidden="true" style="color:white;"></span>
              <span style="color:white;">Home</span>
              <% end %>
              </li>
              <li>
              <%= link_to users_path do %>
              <span class="glyphicon glyphicon-user" aria-hidden="true" style="color:white;"></span>
              <span style="color:white;"> Users </span>
              <% end %>
              </li>
              <li>
              <%= link_to books_path do %>
              <span class="glyphicon glyphicon-book" aria-hidden="true" style="color:white;"></span>
              <span style="color:white;"> Books </span>
              <% end %>
              </li> 
              <li>
              <%= link_to destroy_user_session_path,method: :delete  do %>
              <span class="glyphicon glyphicon-log-out" aria-hidden="true" style="color:white;"></span>
              <span style="color:white;"> logout </span>
              <% end %>
              </li>
            </ul>
     <% else %>
        <ul class = "nav navbar-nav navbar-right">
          <li>
            <%= link_to root_path do %>
            <span class="glyphicon glyphicon-home" aria-hidden="true" style="color:white;"></span>
              <span style="color:white;">Home</span>
            <% end %>
          </li>
          <li>
            <%= link_to about_home_path do %>
            <span class="glyphicon glyphicon-link" aria-hidden="true" style="color:white;"></span>
            <span style="color:white;"> About </span>
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path do %>
            <span class="glyphicon glyphicon-edit" aria-hidden="true" style="color:white;"></span>
            <span style="color:white;"> sign up </span>
            <% end %>
          </li>        
          <li>
            <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-log-in" aria-hidden="true" style="color:white;"></span>
            <span style="color:white;"> login </span>
            <% end %>
          </li>
        </ul>      
      <% end %>  
          </div>
        </div>    
      </div>
    </header> 
    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>
     <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
	
<h2>User info</h2>

<% if @user.errors.any? %>
<h1><%= pluralize(@user.errors.count, "error") %>prohibited this obj from being saved:</h1>
<% @user.errors.full_messages.each do |message| %>
	<li><%= message %></li>
<% end %>
<% end %>

<%= form_for(@user) do |f| %>
<h4>Name</h4>
<%= f.text_field :name,autofocus: true %>
<h4>Image</h4>
<%= f.attachment_field :profile_image %>
<h4>Introduction</h4>
<%= f.text_area :introduction %>
<%= f.submit "Update User" %>

<% end %>

</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">	
		<div class="col-xs-3">
<h1>User info</h1>
<%= attachment_image_tag @user,:profile_image,:fill,60,60,format:"jpg", fallback: "no_image.jpg", size:'60x60' %>
<table class="table">	
	<tbody>
	<tr></tr>
	<tr>		
		<td>name</td>
		<td><%= @user.name %></td>
	</tr>
	<tr>	
		<td>introduction</td>
		<td><%= @user.introduction %></td>
	</tr>
	</tbody>
</table>

<% if @user.id == current_user.id %>
<%= link_to edit_user_path(@user.id) do %>
<div class="btn-group" role="group">
	<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
</div>
<% end %>
<% end %>

<h1>New book</h1>
<%= form_for(@book) do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opininion</h4>
<%= f.text_area :body %>
<%= f.submit "Create Book" %>
<% end %>
		</div>
		<div class="col-xs-9">	

<h1>Users</h1>
<table class = "table">
<tr>
	<th>image</th>
	<th>name</th>
</tr>	
<% @users.each do |user| %>
<tr>
	<td><%= attachment_image_tag user ,:profile_image,:fill,60,60, format:"jpg",fallback: "no_image.jpg", size:'60x60'%></td>
	<td><%= user.name %></td>
	<td><%= link_to "Show",user_path(user.id) %></td>
</tr>
<% end %>
</table>
		</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">	
		<div class="col-xs-3">	
<!-- ユーザ情報 -->



<h2>User info</h2>
<%= attachment_image_tag @user,:profile_image,:fill,60,60,format:"jpg",fallback: "no_image.jpg", size:'60x60' %>
<table class="table">	
	<tbody>	
		<tr></tr>
		<tr>	
			<td>name</td>
			<td><%= @user.name %></td>
		</tr>
		<tr>	
			<td>introduction</td>
			<td><%= @user.introduction %></td>
		</tr>
	</tbody>
</table>
<% if @user.id == current_user.id %>
<%= link_to edit_user_path(@user.id) do %>
<div class="btn-group" role="group">
	<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
</div>
<% end %>	
<% end %>

<!-- 新規投稿 -->
<h2>New book</h2>
<%= form_for(@book) do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_area :body %>	
<%= f.submit "Create Book"  %>

<% end %>
		</div>
		<div class="col-xs-9">	

<!-- 投稿した本一覧 -->
<h2>Books</h2>
<table class="table">
	<thead>
		<tr>
			<th></th>	
			<th>Title</th>
			<th>Opinion</th>
		</tr>
	</thead>	
	<tbody>	
		<% @books.each do |book| %>
		<tr>	
			<th><%= attachment_image_tag @user,:profile_image,:fill,60,60,format:"jpg",fallback: "no_image.jpg", size:'60x60' %>	</th>
			<td><%= link_to book.title,book_path(book.id) %></td>
			<td><%= book.body  %></td>
		</tr>
		<% end %>
	</tbody>
</table>



		</div>
</div>